project:
  type: website
  output-dir: docs

website:
  title: "Mekhala Kumar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ProjectsinR.qmd
      - posters.qmd
      - Visualizations.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    mainfont: "Times New Roman"
    fontsize: 1.25rem
    linkcolour: "#7400b8"

editor: visual

