project:
  type: website
  output-dir: docs

website:
  title: "Mekhala Kumar"
  navbar:
    left:
      - href: index.html
        text: Home
      - ProjectsinR.html
      - posters.html
      - Visualizations.html
      - href: newsletters.html
        text: Newsletters

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    mainfont: "Times New Roman"
    fontsize: 1.25rem
    linkcolour: "#7400b8"

editor: visual

