project:
  type: website
  output-dir: docs

website:
  title: "Mekhala Kumar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ProjectsinR.qmd
        text: Projects in R
      - href: posters.qmd
        text: Papers and Posters
      - href: Visualizations.qmd
        text: Tableau Visualizations
      - href: newsletters.qmd
        text: Newsletters

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    mainfont: "Times New Roman"
    fontsize: 1.25rem
    linkcolour: "#7400b8"

editor: visual

