---
title: "Newsletters"
---

At Trendency Research, I contributed to newsletters focused on political issues. Below are some highlights with links:

[Biden and Age](https://polticial-trendwatch.beehiiv.com/p/biden-age)\
Led ideation, text analysis and visualization of voter concerns about US presidential candidates' age as well as general perceptions of candidates. Contributed to writing. 

[Younger Voters and the Supreme Court](https://polticial-trendwatch.beehiiv.com/p/younger-voters-supreme-court)

Collaborated with the team to design survey questions aimed at capturing the perceptions of voters under 40 regarding the U.S. Supreme Court, with particular emphasis on the 2024 homelessness ruling that banned sleeping in public places. Played a primary role in analyzing responses, creating visualizations and writing.

Worked jointly with team members on analysis these newsletters related to key events in Summer 2024 affecting the US presidential race:

[Can Biden Still Win](https://polticial-trendwatch.beehiiv.com/p/can-biden-still-win)

[Effects of the Mid-Summer Switch Up](https://polticial-trendwatch.beehiiv.com/p/effects-midsummer-switchup)

[A Summer for the Ages](https://polticial-trendwatch.beehiiv.com/p/summer-ages)
